databaseType = "PostgreSql"
id = "658458e7-1ef6-4984-bdb3-851f432f5b8f"
name = "mustartitani-flyway"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flywayDesktop]
enableMigrations = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"
